config/routes.rb
Rails.application.routes.draw do
  get 'rooms/index'
  devise_for :users
  get 'posts/index'
  root 'users#index'
  resources :posts do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show, :index]
  resources :rooms, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to :prefecture
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_many :post_prefectures
  has_many :prefectures, through: :post_prefectures

  validates :title, presence: true
  validates :message, presence: true
  validates :image, presence: true
  validates :prefecture_id, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' }, { id: 2, name: '北海道' }, { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' }, { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, 
    { id: 7, name: '山形県' }, { id: 8, name: '福島県' }, { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' }, { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' }, { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' }, { id: 17, name: '富山県' }, { id: 18, name: '石川県' },
    { id: 19, name: '福井県' }, { id: 20, name: '山梨県' }, { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' }, { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, 
    { id: 25, name: '三重県' }, { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, 
    { id: 28, name: '大阪府' }, { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, 
    { id: 31, name: '和歌山県' }, { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, 
    { id: 34, name: '岡山県' }, { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, 
    { id: 37, name: '徳島県' }, { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, 
    { id: 40, name: '高知県' }, { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, 
    { id: 43, name: '長崎県' }, { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, 
    { id: 46, name: '宮崎県' }, { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
]

include ActiveHash::Associations
has_many :posts

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :room_users
  has_many :users, through: :room_users

end

app/models/room_user.rb
class RoomUser < ApplicationRecord

  belongs_to :room
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :comments
  has_many :room_users
  has_many :rooms, through: :room_users

  validates :nickname, presence: true, length: { maximum: 6 }
  validates :product, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :product])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments
      render "posts/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :move_to_index, only: [:edit]
  
  def index
    @posts = Post.all.order('created_at DESC')
    @prefecture = Prefecture.find(params[:prefecture_id])
    @posts = @prefecture.posts.includes(:post)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to root_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :message, :image, prefecture_ids: []).merge(user_id: current_user.id)
  end

  def move_to_index
    @post = Post.find(params[:id])
    unless current_user.id == @post.user.id
      redirect_to action: :index
    end
  end

end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def new
    @room = Room.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FamousProduct</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("25146485_s.jpg", class: :logo), root_path %>
          </div>
          <%# ログインしているときは以下を表示するようにしましょう %>
            <div class="nav__right">
              <% if user_signed_in? %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
                <%= link_to "投稿する", new_post_path, class: :nav__btn %>
              <% else %>
          <%# // ログインしているときは上記を表示するようにしましょう %>
          <%# ログインしていないときは以下を表示するようにしましょう %>
                <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
                <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
              <% end %>
            </div>
          <%# // ログインしていないときは上記を表示するようにしましょう %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © FAMOUS PRODUCT All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "名物名" %><br />
    <%= f.text_field :title, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :message, "メッセージ" %><br />
    <%= f.text_area :message, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "投稿したい画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="field">
    その名物のある県
  <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"post-prefecture"}) %>
  </div>
  
  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card">
  <%= link_to image_tag(post.image, class: :card__img ), post_path(post.id) %>
  <div class="card__body">
    <%= link_to post.title, post_path(post.id), class: :card__title%>
    <p class="card__summary">
      <%= post.message %>
    </p>
    <%= link_to "by#{post.user.nickname}", "/users/#{post.user.id}", class: :card__user %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿の編集</h2>
      <%# 部分テンプレートでフォームを表示する %>
      <%= render partial: 'form', locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="card__wrapper">
  <%# 投稿機能実装後、部分テンプレートでプロトタイプ投稿一覧を表示する %>
  <%= render partial: 'post', collection: @posts %>
</div>

app/views/posts/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%# 部分テンプレートでフォームを表示する %>
        <%= render 'form', locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @post.title %>
      </p>
      <%= link_to "by#{@post.user.nickname}", user_path(@post.user.id), class: :prototype__user %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
      <% if user_signed_in? && current_user.id == @post.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_post_path(@post.id), class: :prototype__btn %>
          <%= link_to "削除する", post_path(@post.id), method: :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <%# // プロトタイプの投稿者とログインしているユーザーが同じであれば上記を表示する %>
      <div class="prototype__image">
        <%= image_tag @post.image %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">タイトル</p>
          <p class="detail__message">
            <%= @post.title %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">メッセージ</p>
          <p class="detail__message">
            <%= @post.message %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
        <%# ログインしているユーザーには以下のコメント投稿フォームを表示する %>
        <% if user_signed_in? %>
          <%= form_with model: [@post, @comment],local: true do |f| %>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <%# // ログインしているユーザーには上記を表示する %>
        <ul class="comments_lists">
          <%# 投稿に紐づくコメントを一覧する処理を記述する %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content %>
              <%= link_to "#{comment.user.nickname}", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
          <%# // 投稿に紐づくコメントを一覧する処理を記述する %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/rooms/index.html.erb
<h1>Rooms#index</h1>
<p>Find me in app/views/rooms/index.html.erb</p>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>都道府県</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :都道府県名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: '都道府県名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
    <div class='chat-room-form__field--right'>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<main class="main">
  <div class="inner">
    <%# ログインしているときは以下を表示する %>
      <% if user_signed_in? %>
      <div class="greeting">
        こんにちは、 
        <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: :greeting__link %>
      </div>
      <% end %>
    <%# // ログインしているときは上記を表示する %>
    <h1>四国地方</h1>
    <p><%= link_to "徳島県", posts_path %></p>
    <div class="card__wrapper">
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報" %>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= "#{@user.nickname}" %></td>
          </tr>
          <tr>
            <th class="table__col1">好きな名物</th>
            <td class="table__col2"><%= "#{@user.product}" %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの投稿"%>
      </h2>
      <div class="user__card">
        <%# 部分テンプレートでそのユーザーが投稿したプロトタイプ投稿一覧を表示する %>
        <%= render partial: 'posts/post', collection: @user.posts %>
      </div>
    </div>
  </div>
</div>